SELECT
						  COMPANY.COMPANY_ID,
                           COMPANY.COMPANY_NAME,
                           COMPANY.COMPANY_LOGO_PATH,
                           PROGRAM.PROGRAM_MODULE,
                           PM.PROGRAM_MODULE_NAME,
                           PM.PROGRAM_MODULE_PRIORITY,
                           PROGRAM.PROGRAM_CODE,
                           PROGRAM.PROGRAM_NAME
                    FROM WKSP_WSPDMDEV.INTERNAL_USER_ROLE
                             INNER JOIN WKSP_WSPDMDEV.INTERNAL_ROLE ON INTERNAL_ROLE.INTERNAL_ROLE_ID = INTERNAL_USER_ROLE.ROLE_ID
                             INNER JOIN WKSP_WSPDMDEV.INTERNAL_ROLE_PERMISSION ON INTERNAL_ROLE_PERMISSION.INTERNAL_ROLE_ID = INTERNAL_ROLE.INTERNAL_ROLE_ID
                             INNER JOIN WKSP_WSPDMDEV.PERMISSION ON PERMISSION.PERMISSION_ID = INTERNAL_ROLE_PERMISSION.PERMISSION_ID
                             INNER JOIN WKSP_WSPDMDEV."USER" U ON U.USER_ID = INTERNAL_USER_ROLE.USER_ID
                             INNER JOIN WKSP_WSPDMDEV.COMPANY ON COMPANY.COMPANY_ID = INTERNAL_ROLE.COMPANY_ID
                             INNER JOIN WKSP_WSPDMDEV.PROGRAM ON PROGRAM.PROGRAM_CODE = PERMISSION.PROGRAM_CODE
                             INNER JOIN WKSP_WSPDMDEV.PROGRAM_MAPPING ON PROGRAM_CODE_PDM = PROGRAM.PROGRAM_CODE
                             INNER JOIN WKSP_WSPDMDEV.PROGRAM_MODULE PM ON PM.PROGRAM_MODULE_CODE = PROGRAM.PROGRAM_MODULE
                    WHERE  
                    INTERNAL_USER_ROLE.USER_ID = 131  
                      AND PERMISSION_ACTION = 'VIEW'
                      AND INTERNAL_ROLE.IS_ACTIVE = 1
                      AND U.IS_ACTIVE = '1'
                      AND U.IS_INTERNAL = '1'
                      AND PROGRAM_MAPPING.IS_ACTIVE = '1'
                    GROUP BY COMPANY.COMPANY_ID, COMPANY.COMPANY_NAME, COMPANY.COMPANY_LOGO_PATH, PROGRAM_MODULE,
                             PM.PROGRAM_MODULE_NAME, PM.PROGRAM_MODULE_PRIORITY, PROGRAM.PROGRAM_CODE, PROGRAM.PROGRAM_NAME
                    ORDER BY PM.PROGRAM_MODULE_PRIORITY